//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.resSettings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 상세를 입력해 주세요..
        /// </summary>
        internal static string AvailableTimeAlertDetail {
            get {
                return ResourceManager.GetString("AvailableTimeAlertDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 포인트/분.
        /// </summary>
        internal static string AvailableTimePointPerMinute {
            get {
                return ResourceManager.GetString("AvailableTimePointPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 합계.
        /// </summary>
        internal static string AvailableTimeSum {
            get {
                return ResourceManager.GetString("AvailableTimeSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BtnMailCancel {
            get {
                return ResourceManager.GetString("BtnMailCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string BtnMailSend {
            get {
                return ResourceManager.GetString("BtnMailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48시간 이상의 기간에 대한 성능 데이터 조회는 지원되지 않습니다..
        /// </summary>
        internal static string CommonAlertDuration {
            get {
                return ResourceManager.GetString("CommonAlertDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 알림수준.
        /// </summary>
        internal static string CommonAlertLevel {
            get {
                return ResourceManager.GetString("CommonAlertLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 즉시알림.
        /// </summary>
        internal static string CommonAlertNow {
            get {
                return ResourceManager.GetString("CommonAlertNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string CommonBtnApply {
            get {
                return ResourceManager.GetString("CommonBtnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CommonBtnCancel {
            get {
                return ResourceManager.GetString("CommonBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string CommonBtnDelete {
            get {
                return ResourceManager.GetString("CommonBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string CommonBtnModify {
            get {
                return ResourceManager.GetString("CommonBtnModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string CommonBtnRegist {
            get {
                return ResourceManager.GetString("CommonBtnRegist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 수집기간(초).
        /// </summary>
        internal static string CommonCollectionPeriod {
            get {
                return ResourceManager.GetString("CommonCollectionPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설정 DB연결에 실패하였습니다..
        /// </summary>
        internal static string CommonDBConFail {
            get {
                return ResourceManager.GetString("CommonDBConFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 상세.
        /// </summary>
        internal static string CommonDetail {
            get {
                return ResourceManager.GetString("CommonDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 디스플레이명.
        /// </summary>
        internal static string CommonDisplayName {
            get {
                return ResourceManager.GetString("CommonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 조회 기간.
        /// </summary>
        internal static string CommonDuration {
            get {
                return ResourceManager.GetString("CommonDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인스턴스.
        /// </summary>
        internal static string CommonInstance {
            get {
                return ResourceManager.GetString("CommonInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 임계값.
        /// </summary>
        internal static string CommonLimit {
            get {
                return ResourceManager.GetString("CommonLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 멤버 이름.
        /// </summary>
        internal static string CommonMemName {
            get {
                return ResourceManager.GetString("CommonMemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 바차트 데이터가 없습니다..
        /// </summary>
        internal static string CommonNoBarChartData {
            get {
                return ResourceManager.GetString("CommonNoBarChartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 차트 데이터가 조회되지 않았습니다..
        /// </summary>
        internal static string CommonNoChartData {
            get {
                return ResourceManager.GetString("CommonNoChartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 차트를 생성할 데이터가 없거나, 입력 조건이 유효하지 않습니다 ..
        /// </summary>
        internal static string CommonNoChartDataUncorrectData {
            get {
                return ResourceManager.GetString("CommonNoChartDataUncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터가 없습니다..
        /// </summary>
        internal static string CommonNoData {
            get {
                return ResourceManager.GetString("CommonNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 성능카운터.
        /// </summary>
        internal static string CommonPerfCounter {
            get {
                return ResourceManager.GetString("CommonPerfCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 성능 인스턴스.
        /// </summary>
        internal static string CommonPerfInstance {
            get {
                return ResourceManager.GetString("CommonPerfInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 성능객체.
        /// </summary>
        internal static string CommonPerfObject {
            get {
                return ResourceManager.GetString("CommonPerfObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %Processor Time - 전체 사용율과 Priviledged(시스템) 사용율을 표시합니다..
        /// </summary>
        internal static string CommonProcTimeAlert {
            get {
                return ResourceManager.GetString("CommonProcTimeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 세부 실행 기록.
        /// </summary>
        internal static string CommonRecordDetailRun {
            get {
                return ResourceManager.GetString("CommonRecordDetailRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 조회.
        /// </summary>
        internal static string CommonRetrieve {
            get {
                return ResourceManager.GetString("CommonRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 저장.
        /// </summary>
        internal static string CommonSave {
            get {
                return ResourceManager.GetString("CommonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 초.
        /// </summary>
        internal static string CommonSecond {
            get {
                return ResourceManager.GetString("CommonSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버 선택.
        /// </summary>
        internal static string CommonSelectServer {
            get {
                return ResourceManager.GetString("CommonSelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메일 발송.
        /// </summary>
        internal static string CommonSendMail {
            get {
                return ResourceManager.GetString("CommonSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버유형.
        /// </summary>
        internal static string CommonServerType {
            get {
                return ResourceManager.GetString("CommonServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시간.
        /// </summary>
        internal static string CommonTime {
            get {
                return ResourceManager.GetString("CommonTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 미사용.
        /// </summary>
        internal static string CommonUnuse {
            get {
                return ResourceManager.GetString("CommonUnuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사용.
        /// </summary>
        internal static string CommonUse {
            get {
                return ResourceManager.GetString("CommonUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 모바일알림사용.
        /// </summary>
        internal static string CommonUseMobileAlert {
            get {
                return ResourceManager.GetString("CommonUseMobileAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사용여부.
        /// </summary>
        internal static string CommonUseOrUnuse {
            get {
                return ResourceManager.GetString("CommonUseOrUnuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 규칙활성화.
        /// </summary>
        internal static string CommonUseRuls {
            get {
                return ResourceManager.GetString("CommonUseRuls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 사용된 쿠폰입니다..
        /// </summary>
        internal static string CouponAreadyUse {
            get {
                return ResourceManager.GetString("CouponAreadyUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록 할 쿠폰번호를 입력하세요..
        /// </summary>
        internal static string CouponInputNumber {
            get {
                return ResourceManager.GetString("CouponInputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 쿠폰 만기 날짜.
        /// </summary>
        internal static string CouponLimitDate {
            get {
                return ResourceManager.GetString("CouponLimitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사용가능한 쿠폰이 없습니다..
        /// </summary>
        internal static string CouponNotHaven {
            get {
                return ResourceManager.GetString("CouponNotHaven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 쿠폰 번호.
        /// </summary>
        internal static string CouponNumber {
            get {
                return ResourceManager.GetString("CouponNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 쿠폰 포인트.
        /// </summary>
        internal static string CouponPoint {
            get {
                return ResourceManager.GetString("CouponPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 쿠폰 등록 날짜.
        /// </summary>
        internal static string CouponRegDate {
            get {
                return ResourceManager.GetString("CouponRegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 쿠폰이 정상적으로 등록 되었습니다..
        /// </summary>
        internal static string CouponSucceceRegist {
            get {
                return ResourceManager.GetString("CouponSucceceRegist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 다른 쿠폰을 사용하셨습니다..
        /// </summary>
        internal static string CouponUseAnother {
            get {
                return ResourceManager.GetString("CouponUseAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 쿠폰 사용 날짜.
        /// </summary>
        internal static string CouponUseDate {
            get {
                return ResourceManager.GetString("CouponUseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 잘못된 쿠폰 입니다..
        /// </summary>
        internal static string CouponWrong {
            get {
                return ResourceManager.GetString("CouponWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string LblMailAddFile {
            get {
                return ResourceManager.GetString("LblMailAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string LblMailHeader {
            get {
                return ResourceManager.GetString("LblMailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry details.
        /// </summary>
        internal static string LblMailMessage {
            get {
                return ResourceManager.GetString("LblMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMail.
        /// </summary>
        internal static string LblMailSender {
            get {
                return ResourceManager.GetString("LblMailSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 로그인에 실패하였습니다.
        /// </summary>
        internal static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이디 또는 비밀번호를 잘못 입력하셨습니다..
        /// </summary>
        internal static string LoginWrongIDPasswd {
            get {
                return ResourceManager.GetString("LoginWrongIDPasswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account is already involved in other group.
        /// </summary>
        internal static string MemberRegistAlertAlreadyInGruopMember {
            get {
                return ResourceManager.GetString("MemberRegistAlertAlreadyInGruopMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration of the user has been failed..
        /// </summary>
        internal static string MemberRegistAlertFailMemberRegist {
            get {
                return ResourceManager.GetString("MemberRegistAlertFailMemberRegist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a user, or user group has been failed..
        /// </summary>
        internal static string MemberRegistAlertFailWorkDB {
            get {
                return ResourceManager.GetString("MemberRegistAlertFailWorkDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a user name.
        /// </summary>
        internal static string MemberRegistAlertInpuName {
            get {
                return ResourceManager.GetString("MemberRegistAlertInpuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an email address.
        /// </summary>
        internal static string MemberRegistAlertInputMail {
            get {
                return ResourceManager.GetString("MemberRegistAlertInputMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the information of user to register.
        /// </summary>
        internal static string MemberRegistAlertInputMemberInfo {
            get {
                return ResourceManager.GetString("MemberRegistAlertInputMemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password.
        /// </summary>
        internal static string MemberRegistAlertInputPasswd {
            get {
                return ResourceManager.GetString("MemberRegistAlertInputPasswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number.
        /// </summary>
        internal static string MemberRegistAlertInputPhonNumber {
            get {
                return ResourceManager.GetString("MemberRegistAlertInputPhonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the selected user?.
        /// </summary>
        internal static string MemberRegistAlertMemberDelete {
            get {
                return ResourceManager.GetString("MemberRegistAlertMemberDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The both passwords that you entered, are not same..
        /// </summary>
        internal static string MemberRegistAlertNoAgreementPasswd {
            get {
                return ResourceManager.GetString("MemberRegistAlertNoAgreementPasswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s required to have a manager or owner&apos;s permission..
        /// </summary>
        internal static string MemberRegistAlertNotAuthorized {
            get {
                return ResourceManager.GetString("MemberRegistAlertNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s required to select a user from the list..
        /// </summary>
        internal static string MemberRegistAlertSelectMember {
            get {
                return ResourceManager.GetString("MemberRegistAlertSelectMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration of the user has been completed..
        /// </summary>
        internal static string MemberRegistAlertSuccessMemberRegist {
            get {
                return ResourceManager.GetString("MemberRegistAlertSuccessMemberRegist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is valid.
        /// </summary>
        internal static string MemberRegistAlertUnUseMail {
            get {
                return ResourceManager.GetString("MemberRegistAlertUnUseMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is already being used..
        /// </summary>
        internal static string MemberRegistAlertUseMail {
            get {
                return ResourceManager.GetString("MemberRegistAlertUseMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this email address.
        /// </summary>
        internal static string MemberRegistBtnMailCheck {
            get {
                return ResourceManager.GetString("MemberRegistBtnMailCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister.
        /// </summary>
        internal static string MemberRegistBtnMemberDel {
            get {
                return ResourceManager.GetString("MemberRegistBtnMemberDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string MemberRegistLblCompanyName {
            get {
                return ResourceManager.GetString("MemberRegistLblCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group owner, who created this group.
        /// </summary>
        internal static string MemberRegistLblExplanationMember1 {
            get {
                return ResourceManager.GetString("MemberRegistLblExplanationMember1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group manager, who can manage members, and settings.
        /// </summary>
        internal static string MemberRegistLblExplanationMember2 {
            get {
                return ResourceManager.GetString("MemberRegistLblExplanationMember2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions for monitoring dashboard, and reports.
        /// </summary>
        internal static string MemberRegistLblExplanationMember3 {
            get {
                return ResourceManager.GetString("MemberRegistLblExplanationMember3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add users in this monitoring group.
        /// </summary>
        internal static string MemberRegistLblExplanationUser1 {
            get {
                return ResourceManager.GetString("MemberRegistLblExplanationUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying user level requires permissions of Manager, or Owner..
        /// </summary>
        internal static string MemberRegistLblExplanationUser2 {
            get {
                return ResourceManager.GetString("MemberRegistLblExplanationUser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Level.
        /// </summary>
        internal static string MemberRegistLblGrade {
            get {
                return ResourceManager.GetString("MemberRegistLblGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Level.
        /// </summary>
        internal static string MemberRegistLblHeadMember {
            get {
                return ResourceManager.GetString("MemberRegistLblHeadMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add members.
        /// </summary>
        internal static string MemberRegistLblHeadUser {
            get {
                return ResourceManager.GetString("MemberRegistLblHeadUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string MemberRegistLblMail {
            get {
                return ResourceManager.GetString("MemberRegistLblMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string MemberRegistLblPassword {
            get {
                return ResourceManager.GetString("MemberRegistLblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the password.
        /// </summary>
        internal static string MemberRegistLblPasswordCheck {
            get {
                return ResourceManager.GetString("MemberRegistLblPasswordCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string MemberRegistLblPhoneNumber {
            get {
                return ResourceManager.GetString("MemberRegistLblPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring Users Management.
        /// </summary>
        internal static string MemberRegistLblSubject {
            get {
                return ResourceManager.GetString("MemberRegistLblSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 알림 검색 주기(분) .
        /// </summary>
        internal static string MobileAlertsAlertDuration {
            get {
                return ResourceManager.GetString("MobileAlertsAlertDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 설정된 모바일 알림 규칙은 남아있지만,  모니터링 시스템 전체의 모바일 알림 설정을 비활성화 하게됩니다..
        /// </summary>
        internal static string MobileAlertsAlertInfo {
            get {
                return ResourceManager.GetString("MobileAlertsAlertInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 세부 설정 :   모바일 알림 사용함.
        /// </summary>
        internal static string MobileAlertsMobileSetting {
            get {
                return ResourceManager.GetString("MobileAlertsMobileSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최대 반복 알림(개).
        /// </summary>
        internal static string MobileAlertsRepeatCnt {
            get {
                return ResourceManager.GetString("MobileAlertsRepeatCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 반복 카운터 초기화 주기(시간).
        /// </summary>
        internal static string MobileAlertsRepeatDuration {
            get {
                return ResourceManager.GetString("MobileAlertsRepeatDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 알림을 설정할 규칙을 먼저 선택하세요..
        /// </summary>
        internal static string MobileAlertsSelectRul {
            get {
                return ResourceManager.GetString("MobileAlertsSelectRul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시스템 전체의 커밋된 메모리 크기와 가용 메모리(RAM)를 표시하며, 가용 메모리가 매우 작으면 시스템 전체 성능이 저하됩니다..
        /// </summary>
        internal static string PerformanceReportCommitedRam {
            get {
                return ResourceManager.GetString("PerformanceReportCommitedRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 논리디스크 평균 IO 처리 시간 백분율(%)과, 논리디스크 읽기당 소요 시간(밀리초)을 표시합니다.&lt;br/&gt;디스크 성능이 저하된 경우, 읽기당 소요 시간에 길어집니다..
        /// </summary>
        internal static string PerformanceReportDiskIO {
            get {
                return ResourceManager.GetString("PerformanceReportDiskIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 논리디스크 별 여유 공간(MB)을 표시합니다. &lt;br/&gt; 디스크 여유 공간이 부족하면 성능은 물론, 서비스 안정성에 영향을 주게 됩니다..
        /// </summary>
        internal static string PerformanceReportDiskSpace {
            get {
                return ResourceManager.GetString("PerformanceReportDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 네트워크 초당 수신, 송신, 전체 바이트수(모든 인터페이스 중 최대값)을 표시합니다..
        /// </summary>
        internal static string PerformanceReportNetwork {
            get {
                return ResourceManager.GetString("PerformanceReportNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU 처리 대기열의 길이(프로세서당 작업 대기 쓰레드 수), 값이 1 이상이면 CPU 부하에 의해 대기 중인 쓰레드가 존재함을 의미합니다..
        /// </summary>
        internal static string PerformanceReportThreadLength {
            get {
                return ResourceManager.GetString("PerformanceReportThreadLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %Processor Time - 전체 사용율과 Priviledged(시스템) 사용율을 표시합니다..
        /// </summary>
        internal static string PerformanceReportUsingProcTime {
            get {
                return ResourceManager.GetString("PerformanceReportUsingProcTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 모니터할 프로세스명.
        /// </summary>
        internal static string ProcessInstanceAddInsName {
            get {
                return ResourceManager.GetString("ProcessInstanceAddInsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인스턴스를 선택 후 삭제하여 주시기 바랍니다..
        /// </summary>
        internal static string ProcessInstanceChoisFirst {
            get {
                return ResourceManager.GetString("ProcessInstanceChoisFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 카운터명.
        /// </summary>
        internal static string ProcessInstanceCounterName {
            get {
                return ResourceManager.GetString("ProcessInstanceCounterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인스턴스 삭제에 실패하였습니다..
        /// </summary>
        internal static string ProcessInstanceFailDelete {
            get {
                return ResourceManager.GetString("ProcessInstanceFailDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인스턴스 등록에 실패하였습니다..
        /// </summary>
        internal static string ProcessInstanceFailRegist {
            get {
                return ResourceManager.GetString("ProcessInstanceFailRegist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인스턴스명.
        /// </summary>
        internal static string ProcessInstanceInsName {
            get {
                return ResourceManager.GetString("ProcessInstanceInsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 모니터링 항목.
        /// </summary>
        internal static string ProcessInstanceItem {
            get {
                return ResourceManager.GetString("ProcessInstanceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 모니터링 대상 프로세스 목록.
        /// </summary>
        internal static string ProcessInstanceList {
            get {
                return ResourceManager.GetString("ProcessInstanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 해당 인스턴스가 이미 존재합니다..
        /// </summary>
        internal static string ProcessInstancePresenceInstance {
            get {
                return ResourceManager.GetString("ProcessInstancePresenceInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택한 서버.
        /// </summary>
        internal static string ProcessInstanceSelectedServer {
            get {
                return ResourceManager.GetString("ProcessInstanceSelectedServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  인스턴스 삭제를 완료 하였습니다..
        /// </summary>
        internal static string ProcessInstanceSucceceDelete {
            get {
                return ResourceManager.GetString("ProcessInstanceSucceceDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  인스턴스를 등록 하였습니다..
        /// </summary>
        internal static string ProcessInstanceSucceceRegist {
            get {
                return ResourceManager.GetString("ProcessInstanceSucceceRegist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL CPU.
        /// </summary>
        internal static string ReportsCPU {
            get {
                return ResourceManager.GetString("ReportsCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL 서버의 CPU 성능 지표와 사용량을 분석합니다..
        /// </summary>
        internal static string ReportsCPUDiscription {
            get {
                return ResourceManager.GetString("ReportsCPUDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Disk.
        /// </summary>
        internal static string ReportsDisk {
            get {
                return ResourceManager.GetString("ReportsDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL 서버의 Disk 성능 지표와 사용량을 분석합니다..
        /// </summary>
        internal static string ReportsDiskDiscription {
            get {
                return ResourceManager.GetString("ReportsDiskDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사용자 정의 보고서.
        /// </summary>
        internal static string ReportsItemDefinition {
            get {
                return ResourceManager.GetString("ReportsItemDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL 서버.
        /// </summary>
        internal static string ReportsItemSQL {
            get {
                return ResourceManager.GetString("ReportsItemSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 웹서버.
        /// </summary>
        internal static string ReportsItemWeb {
            get {
                return ResourceManager.GetString("ReportsItemWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 공통.
        /// </summary>
        internal static string ReportsItemWin {
            get {
                return ResourceManager.GetString("ReportsItemWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Memory.
        /// </summary>
        internal static string ReportsMemory {
            get {
                return ResourceManager.GetString("ReportsMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL 서버의 Memory 성능 지표와 사용량을 분석합니다..
        /// </summary>
        internal static string ReportsMemoryDiscription {
            get {
                return ResourceManager.GetString("ReportsMemoryDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버 성능 카운터 조회.
        /// </summary>
        internal static string ReportsPerfCounter {
            get {
                return ResourceManager.GetString("ReportsPerfCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 성능카운터를 선택하여 시간대별 값을 조회합니다..
        /// </summary>
        internal static string ReportsPerfCounterDiscription {
            get {
                return ResourceManager.GetString("ReportsPerfCounterDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 성능 분석 보고서.
        /// </summary>
        internal static string ReportsPerfReportSql {
            get {
                return ResourceManager.GetString("ReportsPerfReportSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL 서버의 주요 성능 지표와 사용량을 분석합니다..
        /// </summary>
        internal static string ReportsPerfReportSqlDiscription {
            get {
                return ResourceManager.GetString("ReportsPerfReportSqlDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 성능 분석 보고서.
        /// </summary>
        internal static string ReportsPerfReportWeb {
            get {
                return ResourceManager.GetString("ReportsPerfReportWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 웹서버의 주요 성능 지표와 사용량을 분석합니다..
        /// </summary>
        internal static string ReportsPerfReportWebDiscription {
            get {
                return ResourceManager.GetString("ReportsPerfReportWebDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 성능 분석 보고서.
        /// </summary>
        internal static string ReportsPerfReportWin {
            get {
                return ResourceManager.GetString("ReportsPerfReportWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시스템 주요 자원의 성능 지표를 분석합니다..
        /// </summary>
        internal static string ReportsPerfReportWinDiscription {
            get {
                return ResourceManager.GetString("ReportsPerfReportWinDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서비스 분석 보고서.
        /// </summary>
        internal static string ReportsService {
            get {
                return ResourceManager.GetString("ReportsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 웹서비스 로그 분석을 기반으로 사용자 요청을 분석합니다..
        /// </summary>
        internal static string ReportsServiceDiscription {
            get {
                return ResourceManager.GetString("ReportsServiceDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Point 2.0 보고서.
        /// </summary>
        internal static string ReportsSubject {
            get {
                return ResourceManager.GetString("ReportsSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사용자 서비스 모니터링.
        /// </summary>
        internal static string ReportsUserService {
            get {
                return ResourceManager.GetString("ReportsUserService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 준비중입니다..
        /// </summary>
        internal static string ReportsUserServiceDiscription {
            get {
                return ResourceManager.GetString("ReportsUserServiceDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 임계값은 숫자만 입력 가능합니다..
        /// </summary>
        internal static string RuleEditorByPCIDLimitType {
            get {
                return ResourceManager.GetString("RuleEditorByPCIDLimitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록된 인스턴스 목록.
        /// </summary>
        internal static string RuleEditorByPCIDRegisteredInstanceList {
            get {
                return ResourceManager.GetString("RuleEditorByPCIDRegisteredInstanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 성능 카운터 선택 .
        /// </summary>
        internal static string RuleEditorByPCIDSelectPerfCnt {
            get {
                return ResourceManager.GetString("RuleEditorByPCIDSelectPerfCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 성능 오브젝트 선택.
        /// </summary>
        internal static string RuleEditorByPCIDSelectPerfObj {
            get {
                return ResourceManager.GetString("RuleEditorByPCIDSelectPerfObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 편집할 규칙을 먼저 선택하세요..
        /// </summary>
        internal static string RuleEditorByPCIDSelectRuls {
            get {
                return ResourceManager.GetString("RuleEditorByPCIDSelectRuls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 임계값을 입력해 주세요..
        /// </summary>
        internal static string RulesEditorAlertInputLimit {
            get {
                return ResourceManager.GetString("RulesEditorAlertInputLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 항목을 선택해 주세요..
        /// </summary>
        internal static string RulesEditorAlertSelectItem {
            get {
                return ResourceManager.GetString("RulesEditorAlertSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사용자 목록이 없습니다..
        /// </summary>
        internal static string ServerMemberNoUserList {
            get {
                return ResourceManager.GetString("ServerMemberNoUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 전체 사용자 목록에서, 추가할 사용자를 선택하세요..
        /// </summary>
        internal static string ServerMemberSelectUserAlert {
            get {
                return ResourceManager.GetString("ServerMemberSelectUserAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 전체 사용자 목록.
        /// </summary>
        internal static string ServerMemberTotalMember {
            get {
                return ResourceManager.GetString("ServerMemberTotalMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 할당된 사용자 목록.
        /// </summary>
        internal static string ServerMemberUserList {
            get {
                return ResourceManager.GetString("ServerMemberUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 에이전트 버전.
        /// </summary>
        internal static string ServerRegistAgentVer {
            get {
                return ResourceManager.GetString("ServerRegistAgentVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택한 서버를 삭제 하시겠습니까?.
        /// </summary>
        internal static string ServerRegistAlertDelete {
            get {
                return ResourceManager.GetString("ServerRegistAlertDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택한 서버를 삭제 하였습니다..
        /// </summary>
        internal static string ServerRegistAlertDeleteServerSuccess {
            get {
                return ResourceManager.GetString("ServerRegistAlertDeleteServerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 동일한 서버명이 이미 존재합니다..
        /// </summary>
        internal static string ServerRegistAlertExistServerName {
            get {
                return ResourceManager.GetString("ServerRegistAlertExistServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버의 이름 및 그룹명을 입력해 주세요..
        /// </summary>
        internal static string ServerRegistAlertInputName {
            get {
                return ResourceManager.GetString("ServerRegistAlertInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록된 서버가 없습니다..
        /// </summary>
        internal static string ServerRegistAlertNoExist {
            get {
                return ResourceManager.GetString("ServerRegistAlertNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사용 기간이 남아 있는 서버입니다..
        /// </summary>
        internal static string ServerRegistAlertRemainsPeriod {
            get {
                return ResourceManager.GetString("ServerRegistAlertRemainsPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 삭제할 서버를 선택하세요..
        /// </summary>
        internal static string ServerRegistAlertSelectDeleteServer {
            get {
                return ResourceManager.GetString("ServerRegistAlertSelectDeleteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 편집할 서버를 선택하세요..
        /// </summary>
        internal static string ServerRegistAlertselectUpdateServer {
            get {
                return ResourceManager.GetString("ServerRegistAlertselectUpdateServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버 정보를 수정하였습니다..
        /// </summary>
        internal static string ServerRegistAlertServerInfoUpdateSuccess {
            get {
                return ResourceManager.GetString("ServerRegistAlertServerInfoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택한 서버의 정보를 수정 하시겠습니까?.
        /// </summary>
        internal static string ServerRegistAlertUpdate {
            get {
                return ResourceManager.GetString("ServerRegistAlertUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 에이전트 다운로드.
        /// </summary>
        internal static string ServerRegistBtnAgentDown {
            get {
                return ResourceManager.GetString("ServerRegistBtnAgentDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 쿠폰함.
        /// </summary>
        internal static string ServerRegistBtnCoupon {
            get {
                return ResourceManager.GetString("ServerRegistBtnCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버삭제.
        /// </summary>
        internal static string ServerRegistBtnServerDelete {
            get {
                return ResourceManager.GetString("ServerRegistBtnServerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버정보수정.
        /// </summary>
        internal static string ServerRegistBtnServerInfoRegist {
            get {
                return ResourceManager.GetString("ServerRegistBtnServerInfoRegist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버등록.
        /// </summary>
        internal static string ServerRegistBtnServerReg {
            get {
                return ResourceManager.GetString("ServerRegistBtnServerReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재정보 업데이트.
        /// </summary>
        internal static string ServerRegistBtnUpdate {
            get {
                return ResourceManager.GetString("ServerRegistBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 일.
        /// </summary>
        internal static string ServerRegistDate {
            get {
                return ResourceManager.GetString("ServerRegistDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버 표시 그룹명.
        /// </summary>
        internal static string ServerRegistDPGroup {
            get {
                return ResourceManager.GetString("ServerRegistDPGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버 표시 이름.
        /// </summary>
        internal static string ServerRegistDPName {
            get {
                return ResourceManager.GetString("ServerRegistDPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버를 등록하였습니다..
        /// </summary>
        internal static string ServerRegisterAddAlert {
            get {
                return ResourceManager.GetString("ServerRegisterAddAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 대시보드 화면에 표시될 서버의 그룹명을 기재합니다..
        /// </summary>
        internal static string ServerRegisterAddLblDPGroupName {
            get {
                return ResourceManager.GetString("ServerRegisterAddLblDPGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 대시보드 화면에 표시될 서버명을 고유값으로 지정합니다..
        /// </summary>
        internal static string ServerRegisterAddLblDPName {
            get {
                return ResourceManager.GetString("ServerRegisterAddLblDPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 모니터링할 서비스 유형을 지정합니다. (등록 이후 수정 불가).
        /// </summary>
        internal static string ServerRegisterAddLblServerType {
            get {
                return ResourceManager.GetString("ServerRegisterAddLblServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 알림에 사용할 언어를 선택합니다..
        /// </summary>
        internal static string ServerRegisterAddLblUsingLang {
            get {
                return ResourceManager.GetString("ServerRegisterAddLblUsingLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록 할 서버의 정보를 입력하세요..
        /// </summary>
        internal static string ServerRegisterAddServerInfo {
            get {
                return ResourceManager.GetString("ServerRegisterAddServerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 만료일.
        /// </summary>
        internal static string ServerRegistExpirationDate {
            get {
                return ResourceManager.GetString("ServerRegistExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 그룹명.
        /// </summary>
        internal static string ServerRegistGroupName {
            get {
                return ResourceManager.GetString("ServerRegistGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 언어.
        /// </summary>
        internal static string ServerRegistLang {
            get {
                return ResourceManager.GetString("ServerRegistLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 분.
        /// </summary>
        internal static string ServerRegistMinute {
            get {
                return ResourceManager.GetString("ServerRegistMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록일.
        /// </summary>
        internal static string ServerRegistRegDate {
            get {
                return ResourceManager.GetString("ServerRegistRegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 잔여포인트.
        /// </summary>
        internal static string ServerRegistRemainingPoint {
            get {
                return ResourceManager.GetString("ServerRegistRemainingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 남은시간.
        /// </summary>
        internal static string ServerRegistRemainingTime {
            get {
                return ResourceManager.GetString("ServerRegistRemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버키.
        /// </summary>
        internal static string ServerRegistServerKey {
            get {
                return ResourceManager.GetString("ServerRegistServerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버명.
        /// </summary>
        internal static string ServerRegistServerName {
            get {
                return ResourceManager.GetString("ServerRegistServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버 등록/수정/삭제.
        /// </summary>
        internal static string ServerRegistSubject {
            get {
                return ResourceManager.GetString("ServerRegistSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시간.
        /// </summary>
        internal static string ServerRegistTime {
            get {
                return ResourceManager.GetString("ServerRegistTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사용언어.
        /// </summary>
        internal static string ServerRegistUseLang {
            get {
                return ResourceManager.GetString("ServerRegistUseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 분당 사용 포인트.
        /// </summary>
        internal static string ServerRegistUseMinPoint {
            get {
                return ResourceManager.GetString("ServerRegistUseMinPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager, or Owner privilege is required to manage Service Point 2.0 settings..
        /// </summary>
        internal static string SettingsAuthorityAlert {
            get {
                return ResourceManager.GetString("SettingsAuthorityAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing Monitoring Service Time Remaining.
        /// </summary>
        internal static string SettingsItemHeadAvailableTime {
            get {
                return ResourceManager.GetString("SettingsItemHeadAvailableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To check remaining time of Service Point 2.0 monitoring agents.
        /// </summary>
        internal static string SettingsItemHeadAvailableTimeExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadAvailableTimeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &amp; Update.
        /// </summary>
        internal static string SettingsItemHeadDownload {
            get {
                return ResourceManager.GetString("SettingsItemHeadDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To download Service Point 2.0 related updates.
        /// </summary>
        internal static string SettingsItemHeadDownloadExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadDownloadExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Alert Settings.
        /// </summary>
        internal static string SettingsItemHeadMobileAlerts {
            get {
                return ResourceManager.GetString("SettingsItemHeadMobileAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To configure alerts of mobile push service for the alerts from Service Point Dashboard.
        /// </summary>
        internal static string SettingsItemHeadMobileAlertsExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadMobileAlertsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Process Monitoring Management.
        /// </summary>
        internal static string SettingsItemHeadProcessInstance {
            get {
                return ResourceManager.GetString("SettingsItemHeadProcessInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To register, or delete a user-defined process from any target server.
        /// </summary>
        internal static string SettingsItemHeadProcessInstanceExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadProcessInstanceExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Management, based on Performance Counters.
        /// </summary>
        internal static string SettingsItemHeadRuleEditorByPCID {
            get {
                return ResourceManager.GetString("SettingsItemHeadRuleEditorByPCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To configure alerts, and their conditions, based on performance counters.
        /// </summary>
        internal static string SettingsItemHeadRuleEditorByPCIDExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadRuleEditorByPCIDExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Management.
        /// </summary>
        internal static string SettingsItemHeadRulesEditor {
            get {
                return ResourceManager.GetString("SettingsItemHeadRulesEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To configure alerts, and their conditions, such as threshold, based on servers, and severity.
        /// </summary>
        internal static string SettingsItemHeadRulesEditorExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadRulesEditorExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning users to monitoring servers.
        /// </summary>
        internal static string SettingsItemHeadServerMember {
            get {
                return ResourceManager.GetString("SettingsItemHeadServerMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To manage users, and servers to monitor. Service Point Dashboard will display information of servers only for assinged users..
        /// </summary>
        internal static string SettingsItemHeadServerMemberExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadServerMemberExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring Servers Management.
        /// </summary>
        internal static string SettingsItemHeadServerRegister {
            get {
                return ResourceManager.GetString("SettingsItemHeadServerRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To register, or edit server information to monitor.
        /// </summary>
        internal static string SettingsItemHeadServerRegisterExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadServerRegisterExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring Users Management.
        /// </summary>
        internal static string SettingsItemHeadUserManagement {
            get {
                return ResourceManager.GetString("SettingsItemHeadUserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To register, or delete users of this monitoring group.
        /// </summary>
        internal static string SettingsItemHeadUserManagementExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadUserManagementExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring Management.
        /// </summary>
        internal static string SettingsItemMonitoringManagement {
            get {
                return ResourceManager.GetString("SettingsItemMonitoringManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers Management.
        /// </summary>
        internal static string SettingsItemServerManagement {
            get {
                return ResourceManager.GetString("SettingsItemServerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Management.
        /// </summary>
        internal static string SettingsItemUserManagement {
            get {
                return ResourceManager.GetString("SettingsItemUserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Settings Main Page.
        /// </summary>
        internal static string SettingsLinkHome {
            get {
                return ResourceManager.GetString("SettingsLinkHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Point 2.0 Administrations.
        /// </summary>
        internal static string SettingsSubject {
            get {
                return ResourceManager.GetString("SettingsSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required fields - Title.
        /// </summary>
        internal static string StrMailHeaderEmtyAlert {
            get {
                return ResourceManager.GetString("StrMailHeaderEmtyAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required fields - Inquiry details.
        /// </summary>
        internal static string StrMailMessageEmtyAlert {
            get {
                return ResourceManager.GetString("StrMailMessageEmtyAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required fields - Email Address.
        /// </summary>
        internal static string StrMailSenderEmtyAlert {
            get {
                return ResourceManager.GetString("StrMailSenderEmtyAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your inquiry has been submitted successfully..
        /// </summary>
        internal static string StrMailSuccessSendAlert {
            get {
                return ResourceManager.GetString("StrMailSuccessSendAlert", resourceCulture);
            }
        }
    }
}
