//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음
    // /str 옵션을 사용하여 ResGen을 다시 실행하거나 Visual Studio 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resSettings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.resSettings", global::System.Reflection.Assembly.Load("App_GlobalResource"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   상세를 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AvailableTimeAlertDetail {
            get {
                return ResourceManager.GetString("AvailableTimeAlertDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   포인트/분과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AvailableTimePointPerMinute {
            get {
                return ResourceManager.GetString("AvailableTimePointPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   합계과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AvailableTimeSum {
            get {
                return ResourceManager.GetString("AvailableTimeSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BtnMailCancel {
            get {
                return ResourceManager.GetString("BtnMailCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BtnMailSend {
            get {
                return ResourceManager.GetString("BtnMailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   48시간 이상의 기간에 대한 성능 데이터 조회는 지원되지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonAlertDuration {
            get {
                return ResourceManager.GetString("CommonAlertDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알림수준과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonAlertLevel {
            get {
                return ResourceManager.GetString("CommonAlertLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   즉시알림과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonAlertNow {
            get {
                return ResourceManager.GetString("CommonAlertNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonBtnApply {
            get {
                return ResourceManager.GetString("CommonBtnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonBtnCancel {
            get {
                return ResourceManager.GetString("CommonBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonBtnDelete {
            get {
                return ResourceManager.GetString("CommonBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonBtnModify {
            get {
                return ResourceManager.GetString("CommonBtnModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonBtnRegist {
            get {
                return ResourceManager.GetString("CommonBtnRegist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수집기간(초)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonCollectionPeriod {
            get {
                return ResourceManager.GetString("CommonCollectionPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정 DB연결에 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonDBConFail {
            get {
                return ResourceManager.GetString("CommonDBConFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상세과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonDetail {
            get {
                return ResourceManager.GetString("CommonDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   디스플레이명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonDisplayName {
            get {
                return ResourceManager.GetString("CommonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조회 기간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonDuration {
            get {
                return ResourceManager.GetString("CommonDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인스턴스과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonInstance {
            get {
                return ResourceManager.GetString("CommonInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   임계값과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonLimit {
            get {
                return ResourceManager.GetString("CommonLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   멤버 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonMemName {
            get {
                return ResourceManager.GetString("CommonMemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   바차트 데이터가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonNoBarChartData {
            get {
                return ResourceManager.GetString("CommonNoBarChartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   차트 데이터가 조회되지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonNoChartData {
            get {
                return ResourceManager.GetString("CommonNoChartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   차트를 생성할 데이터가 없거나, 입력 조건이 유효하지 않습니다 .과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonNoChartDataUncorrectData {
            get {
                return ResourceManager.GetString("CommonNoChartDataUncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonNoData {
            get {
                return ResourceManager.GetString("CommonNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성능카운터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonPerfCounter {
            get {
                return ResourceManager.GetString("CommonPerfCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성능 인스턴스과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonPerfInstance {
            get {
                return ResourceManager.GetString("CommonPerfInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성능객체과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonPerfObject {
            get {
                return ResourceManager.GetString("CommonPerfObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %Processor Time - 전체 사용율과 Priviledged(시스템) 사용율을 표시합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonProcTimeAlert {
            get {
                return ResourceManager.GetString("CommonProcTimeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   세부 실행 기록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonRecordDetailRun {
            get {
                return ResourceManager.GetString("CommonRecordDetailRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조회과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonRetrieve {
            get {
                return ResourceManager.GetString("CommonRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonSave {
            get {
                return ResourceManager.GetString("CommonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonSecond {
            get {
                return ResourceManager.GetString("CommonSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버 선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonSelectServer {
            get {
                return ResourceManager.GetString("CommonSelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메일 발송과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonSendMail {
            get {
                return ResourceManager.GetString("CommonSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버유형과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonServerType {
            get {
                return ResourceManager.GetString("CommonServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonTime {
            get {
                return ResourceManager.GetString("CommonTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   미사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonUnuse {
            get {
                return ResourceManager.GetString("CommonUnuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonUse {
            get {
                return ResourceManager.GetString("CommonUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모바일알림사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonUseMobileAlert {
            get {
                return ResourceManager.GetString("CommonUseMobileAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용여부과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonUseOrUnuse {
            get {
                return ResourceManager.GetString("CommonUseOrUnuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   규칙활성화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonUseRuls {
            get {
                return ResourceManager.GetString("CommonUseRuls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 사용된 쿠폰입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CouponAreadyUse {
            get {
                return ResourceManager.GetString("CouponAreadyUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록 할 쿠폰번호를 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CouponInputNumber {
            get {
                return ResourceManager.GetString("CouponInputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쿠폰 만기 날짜과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CouponLimitDate {
            get {
                return ResourceManager.GetString("CouponLimitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용가능한 쿠폰이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CouponNotHaven {
            get {
                return ResourceManager.GetString("CouponNotHaven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쿠폰 번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CouponNumber {
            get {
                return ResourceManager.GetString("CouponNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쿠폰 포인트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CouponPoint {
            get {
                return ResourceManager.GetString("CouponPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쿠폰 등록 날짜과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CouponRegDate {
            get {
                return ResourceManager.GetString("CouponRegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쿠폰이 정상적으로 등록 되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CouponSucceceRegist {
            get {
                return ResourceManager.GetString("CouponSucceceRegist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 다른 쿠폰을 사용하셨습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CouponUseAnother {
            get {
                return ResourceManager.GetString("CouponUseAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쿠폰 사용 날짜과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CouponUseDate {
            get {
                return ResourceManager.GetString("CouponUseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   잘못된 쿠폰 입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CouponWrong {
            get {
                return ResourceManager.GetString("CouponWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LblMailAddFile {
            get {
                return ResourceManager.GetString("LblMailAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LblMailHeader {
            get {
                return ResourceManager.GetString("LblMailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inquiry details과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LblMailMessage {
            get {
                return ResourceManager.GetString("LblMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EMail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LblMailSender {
            get {
                return ResourceManager.GetString("LblMailSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인에 실패하였습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이디 또는 비밀번호를 잘못 입력하셨습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoginWrongIDPasswd {
            get {
                return ResourceManager.GetString("LoginWrongIDPasswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The user account is already involved in other group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistAlertAlreadyInGruopMember {
            get {
                return ResourceManager.GetString("MemberRegistAlertAlreadyInGruopMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registration of the user has been failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistAlertFailMemberRegist {
            get {
                return ResourceManager.GetString("MemberRegistAlertFailMemberRegist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creating a user, or user group has been failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistAlertFailWorkDB {
            get {
                return ResourceManager.GetString("MemberRegistAlertFailWorkDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a user name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistAlertInpuName {
            get {
                return ResourceManager.GetString("MemberRegistAlertInpuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter an email address과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistAlertInputMail {
            get {
                return ResourceManager.GetString("MemberRegistAlertInputMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the information of user to register과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistAlertInputMemberInfo {
            get {
                return ResourceManager.GetString("MemberRegistAlertInputMemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistAlertInputPasswd {
            get {
                return ResourceManager.GetString("MemberRegistAlertInputPasswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter your phone number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistAlertInputPhonNumber {
            get {
                return ResourceManager.GetString("MemberRegistAlertInputPhonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to delete the selected user?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistAlertMemberDelete {
            get {
                return ResourceManager.GetString("MemberRegistAlertMemberDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The both passwords that you entered, are not same.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistAlertNoAgreementPasswd {
            get {
                return ResourceManager.GetString("MemberRegistAlertNoAgreementPasswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It&apos;s required to have a manager or owner&apos;s permission.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistAlertNotAuthorized {
            get {
                return ResourceManager.GetString("MemberRegistAlertNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It&apos;s required to select a user from the list.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistAlertSelectMember {
            get {
                return ResourceManager.GetString("MemberRegistAlertSelectMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registration of the user has been completed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistAlertSuccessMemberRegist {
            get {
                return ResourceManager.GetString("MemberRegistAlertSuccessMemberRegist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The email address is valid과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistAlertUnUseMail {
            get {
                return ResourceManager.GetString("MemberRegistAlertUnUseMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The email address is already being used.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistAlertUseMail {
            get {
                return ResourceManager.GetString("MemberRegistAlertUseMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check this email address과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistBtnMailCheck {
            get {
                return ResourceManager.GetString("MemberRegistBtnMailCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unregister과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistBtnMemberDel {
            get {
                return ResourceManager.GetString("MemberRegistBtnMemberDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Company Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistLblCompanyName {
            get {
                return ResourceManager.GetString("MemberRegistLblCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group owner, who created this group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistLblExplanationMember1 {
            get {
                return ResourceManager.GetString("MemberRegistLblExplanationMember1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group manager, who can manage members, and settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistLblExplanationMember2 {
            get {
                return ResourceManager.GetString("MemberRegistLblExplanationMember2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Permissions for monitoring dashboard, and reports과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistLblExplanationMember3 {
            get {
                return ResourceManager.GetString("MemberRegistLblExplanationMember3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To add users in this monitoring group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistLblExplanationUser1 {
            get {
                return ResourceManager.GetString("MemberRegistLblExplanationUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modifying user level requires permissions of Manager, or Owner.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistLblExplanationUser2 {
            get {
                return ResourceManager.GetString("MemberRegistLblExplanationUser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Level과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistLblGrade {
            get {
                return ResourceManager.GetString("MemberRegistLblGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Level과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistLblHeadMember {
            get {
                return ResourceManager.GetString("MemberRegistLblHeadMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add members과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistLblHeadUser {
            get {
                return ResourceManager.GetString("MemberRegistLblHeadUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistLblMail {
            get {
                return ResourceManager.GetString("MemberRegistLblMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistLblPassword {
            get {
                return ResourceManager.GetString("MemberRegistLblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm the password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistLblPasswordCheck {
            get {
                return ResourceManager.GetString("MemberRegistLblPasswordCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phone number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistLblPhoneNumber {
            get {
                return ResourceManager.GetString("MemberRegistLblPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monitoring Users Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberRegistLblSubject {
            get {
                return ResourceManager.GetString("MemberRegistLblSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알림 검색 주기(분) 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MobileAlertsAlertDuration {
            get {
                return ResourceManager.GetString("MobileAlertsAlertDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 설정된 모바일 알림 규칙은 남아있지만,  모니터링 시스템 전체의 모바일 알림 설정을 비활성화 하게됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MobileAlertsAlertInfo {
            get {
                return ResourceManager.GetString("MobileAlertsAlertInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   세부 설정 :   모바일 알림 사용함과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MobileAlertsMobileSetting {
            get {
                return ResourceManager.GetString("MobileAlertsMobileSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대 반복 알림(개)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MobileAlertsRepeatCnt {
            get {
                return ResourceManager.GetString("MobileAlertsRepeatCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   반복 카운터 초기화 주기(시간)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MobileAlertsRepeatDuration {
            get {
                return ResourceManager.GetString("MobileAlertsRepeatDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알림을 설정할 규칙을 먼저 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MobileAlertsSelectRul {
            get {
                return ResourceManager.GetString("MobileAlertsSelectRul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템 전체의 커밋된 메모리 크기와 가용 메모리(RAM)를 표시하며, 가용 메모리가 매우 작으면 시스템 전체 성능이 저하됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PerformanceReportCommitedRam {
            get {
                return ResourceManager.GetString("PerformanceReportCommitedRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   논리디스크 평균 IO 처리 시간 백분율(%)과, 논리디스크 읽기당 소요 시간(밀리초)을 표시합니다.&lt;br/&gt;디스크 성능이 저하된 경우, 읽기당 소요 시간에 길어집니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PerformanceReportDiskIO {
            get {
                return ResourceManager.GetString("PerformanceReportDiskIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   논리디스크 별 여유 공간(MB)을 표시합니다. &lt;br/&gt; 디스크 여유 공간이 부족하면 성능은 물론, 서비스 안정성에 영향을 주게 됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PerformanceReportDiskSpace {
            get {
                return ResourceManager.GetString("PerformanceReportDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   네트워크 초당 수신, 송신, 전체 바이트수(모든 인터페이스 중 최대값)을 표시합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PerformanceReportNetwork {
            get {
                return ResourceManager.GetString("PerformanceReportNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CPU 처리 대기열의 길이(프로세서당 작업 대기 쓰레드 수), 값이 1 이상이면 CPU 부하에 의해 대기 중인 쓰레드가 존재함을 의미합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PerformanceReportThreadLength {
            get {
                return ResourceManager.GetString("PerformanceReportThreadLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %Processor Time - 전체 사용율과 Priviledged(시스템) 사용율을 표시합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PerformanceReportUsingProcTime {
            get {
                return ResourceManager.GetString("PerformanceReportUsingProcTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모니터할 프로세스명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcessInstanceAddInsName {
            get {
                return ResourceManager.GetString("ProcessInstanceAddInsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인스턴스를 선택 후 삭제하여 주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcessInstanceChoisFirst {
            get {
                return ResourceManager.GetString("ProcessInstanceChoisFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   카운터명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcessInstanceCounterName {
            get {
                return ResourceManager.GetString("ProcessInstanceCounterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인스턴스 삭제에 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcessInstanceFailDelete {
            get {
                return ResourceManager.GetString("ProcessInstanceFailDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인스턴스 등록에 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcessInstanceFailRegist {
            get {
                return ResourceManager.GetString("ProcessInstanceFailRegist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인스턴스명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcessInstanceInsName {
            get {
                return ResourceManager.GetString("ProcessInstanceInsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모니터링 항목과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcessInstanceItem {
            get {
                return ResourceManager.GetString("ProcessInstanceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모니터링 대상 프로세스 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcessInstanceList {
            get {
                return ResourceManager.GetString("ProcessInstanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 인스턴스가 이미 존재합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcessInstancePresenceInstance {
            get {
                return ResourceManager.GetString("ProcessInstancePresenceInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 서버과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcessInstanceSelectedServer {
            get {
                return ResourceManager.GetString("ProcessInstanceSelectedServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    인스턴스 삭제를 완료 하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcessInstanceSucceceDelete {
            get {
                return ResourceManager.GetString("ProcessInstanceSucceceDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    인스턴스를 등록 하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcessInstanceSucceceRegist {
            get {
                return ResourceManager.GetString("ProcessInstanceSucceceRegist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQL CPU과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsCPU {
            get {
                return ResourceManager.GetString("ReportsCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQL 서버의 CPU 성능 지표와 사용량을 분석합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsCPUDiscription {
            get {
                return ResourceManager.GetString("ReportsCPUDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQL Disk과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsDisk {
            get {
                return ResourceManager.GetString("ReportsDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQL 서버의 Disk 성능 지표와 사용량을 분석합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsDiskDiscription {
            get {
                return ResourceManager.GetString("ReportsDiskDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 정의 보고서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsItemDefinition {
            get {
                return ResourceManager.GetString("ReportsItemDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQL 서버과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsItemSQL {
            get {
                return ResourceManager.GetString("ReportsItemSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웹서버과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsItemWeb {
            get {
                return ResourceManager.GetString("ReportsItemWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows 공통과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsItemWin {
            get {
                return ResourceManager.GetString("ReportsItemWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQL Memory과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsMemory {
            get {
                return ResourceManager.GetString("ReportsMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQL 서버의 Memory 성능 지표와 사용량을 분석합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsMemoryDiscription {
            get {
                return ResourceManager.GetString("ReportsMemoryDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버 성능 카운터 조회과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsPerfCounter {
            get {
                return ResourceManager.GetString("ReportsPerfCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성능카운터를 선택하여 시간대별 값을 조회합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsPerfCounterDiscription {
            get {
                return ResourceManager.GetString("ReportsPerfCounterDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성능 분석 보고서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsPerfReportSql {
            get {
                return ResourceManager.GetString("ReportsPerfReportSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQL 서버의 주요 성능 지표와 사용량을 분석합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsPerfReportSqlDiscription {
            get {
                return ResourceManager.GetString("ReportsPerfReportSqlDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성능 분석 보고서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsPerfReportWeb {
            get {
                return ResourceManager.GetString("ReportsPerfReportWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웹서버의 주요 성능 지표와 사용량을 분석합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsPerfReportWebDiscription {
            get {
                return ResourceManager.GetString("ReportsPerfReportWebDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성능 분석 보고서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsPerfReportWin {
            get {
                return ResourceManager.GetString("ReportsPerfReportWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템 주요 자원의 성능 지표를 분석합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsPerfReportWinDiscription {
            get {
                return ResourceManager.GetString("ReportsPerfReportWinDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서비스 분석 보고서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsService {
            get {
                return ResourceManager.GetString("ReportsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웹서비스 로그 분석을 기반으로 사용자 요청을 분석합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsServiceDiscription {
            get {
                return ResourceManager.GetString("ReportsServiceDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Service Point 2.0 보고서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsSubject {
            get {
                return ResourceManager.GetString("ReportsSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 서비스 모니터링과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsUserService {
            get {
                return ResourceManager.GetString("ReportsUserService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   준비중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportsUserServiceDiscription {
            get {
                return ResourceManager.GetString("ReportsUserServiceDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   임계값은 숫자만 입력 가능합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RuleEditorByPCIDLimitType {
            get {
                return ResourceManager.GetString("RuleEditorByPCIDLimitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록된 인스턴스 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RuleEditorByPCIDRegisteredInstanceList {
            get {
                return ResourceManager.GetString("RuleEditorByPCIDRegisteredInstanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성능 카운터 선택 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RuleEditorByPCIDSelectPerfCnt {
            get {
                return ResourceManager.GetString("RuleEditorByPCIDSelectPerfCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성능 오브젝트 선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RuleEditorByPCIDSelectPerfObj {
            get {
                return ResourceManager.GetString("RuleEditorByPCIDSelectPerfObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   편집할 규칙을 먼저 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RuleEditorByPCIDSelectRuls {
            get {
                return ResourceManager.GetString("RuleEditorByPCIDSelectRuls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   임계값을 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RulesEditorAlertInputLimit {
            get {
                return ResourceManager.GetString("RulesEditorAlertInputLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   항목을 선택해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RulesEditorAlertSelectItem {
            get {
                return ResourceManager.GetString("RulesEditorAlertSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 목록이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerMemberNoUserList {
            get {
                return ResourceManager.GetString("ServerMemberNoUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 사용자 목록에서, 추가할 사용자를 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerMemberSelectUserAlert {
            get {
                return ResourceManager.GetString("ServerMemberSelectUserAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 사용자 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerMemberTotalMember {
            get {
                return ResourceManager.GetString("ServerMemberTotalMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   할당된 사용자 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerMemberUserList {
            get {
                return ResourceManager.GetString("ServerMemberUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에이전트 버전과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistAgentVer {
            get {
                return ResourceManager.GetString("ServerRegistAgentVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 서버를 삭제 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistAlertDelete {
            get {
                return ResourceManager.GetString("ServerRegistAlertDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 서버를 삭제 하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistAlertDeleteServerSuccess {
            get {
                return ResourceManager.GetString("ServerRegistAlertDeleteServerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   동일한 서버명이 이미 존재합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistAlertExistServerName {
            get {
                return ResourceManager.GetString("ServerRegistAlertExistServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버의 이름 및 그룹명을 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistAlertInputName {
            get {
                return ResourceManager.GetString("ServerRegistAlertInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록된 서버가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistAlertNoExist {
            get {
                return ResourceManager.GetString("ServerRegistAlertNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용 기간이 남아 있는 서버입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistAlertRemainsPeriod {
            get {
                return ResourceManager.GetString("ServerRegistAlertRemainsPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제할 서버를 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistAlertSelectDeleteServer {
            get {
                return ResourceManager.GetString("ServerRegistAlertSelectDeleteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   편집할 서버를 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistAlertselectUpdateServer {
            get {
                return ResourceManager.GetString("ServerRegistAlertselectUpdateServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버 정보를 수정하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistAlertServerInfoUpdateSuccess {
            get {
                return ResourceManager.GetString("ServerRegistAlertServerInfoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 서버의 정보를 수정 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistAlertUpdate {
            get {
                return ResourceManager.GetString("ServerRegistAlertUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에이전트 다운로드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistBtnAgentDown {
            get {
                return ResourceManager.GetString("ServerRegistBtnAgentDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쿠폰함과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistBtnCoupon {
            get {
                return ResourceManager.GetString("ServerRegistBtnCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistBtnServerDelete {
            get {
                return ResourceManager.GetString("ServerRegistBtnServerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버정보수정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistBtnServerInfoRegist {
            get {
                return ResourceManager.GetString("ServerRegistBtnServerInfoRegist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버등록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistBtnServerReg {
            get {
                return ResourceManager.GetString("ServerRegistBtnServerReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재정보 업데이트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistBtnUpdate {
            get {
                return ResourceManager.GetString("ServerRegistBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistDate {
            get {
                return ResourceManager.GetString("ServerRegistDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버 표시 그룹명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistDPGroup {
            get {
                return ResourceManager.GetString("ServerRegistDPGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버 표시 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistDPName {
            get {
                return ResourceManager.GetString("ServerRegistDPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버를 등록하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegisterAddAlert {
            get {
                return ResourceManager.GetString("ServerRegisterAddAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대시보드 화면에 표시될 서버의 그룹명을 기재합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegisterAddLblDPGroupName {
            get {
                return ResourceManager.GetString("ServerRegisterAddLblDPGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대시보드 화면에 표시될 서버명을 고유값으로 지정합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegisterAddLblDPName {
            get {
                return ResourceManager.GetString("ServerRegisterAddLblDPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모니터링할 서비스 유형을 지정합니다. (등록 이후 수정 불가)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegisterAddLblServerType {
            get {
                return ResourceManager.GetString("ServerRegisterAddLblServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알림에 사용할 언어를 선택합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegisterAddLblUsingLang {
            get {
                return ResourceManager.GetString("ServerRegisterAddLblUsingLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록 할 서버의 정보를 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegisterAddServerInfo {
            get {
                return ResourceManager.GetString("ServerRegisterAddServerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   만료일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistExpirationDate {
            get {
                return ResourceManager.GetString("ServerRegistExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그룹명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistGroupName {
            get {
                return ResourceManager.GetString("ServerRegistGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistLang {
            get {
                return ResourceManager.GetString("ServerRegistLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   분과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistMinute {
            get {
                return ResourceManager.GetString("ServerRegistMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistRegDate {
            get {
                return ResourceManager.GetString("ServerRegistRegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   잔여포인트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistRemainingPoint {
            get {
                return ResourceManager.GetString("ServerRegistRemainingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   남은시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistRemainingTime {
            get {
                return ResourceManager.GetString("ServerRegistRemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버키과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistServerKey {
            get {
                return ResourceManager.GetString("ServerRegistServerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistServerName {
            get {
                return ResourceManager.GetString("ServerRegistServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버 등록/수정/삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistSubject {
            get {
                return ResourceManager.GetString("ServerRegistSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistTime {
            get {
                return ResourceManager.GetString("ServerRegistTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용언어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistUseLang {
            get {
                return ResourceManager.GetString("ServerRegistUseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   분당 사용 포인트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServerRegistUseMinPoint {
            get {
                return ResourceManager.GetString("ServerRegistUseMinPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manager, or Owner privilege is required to manage Service Point 2.0 settings.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsAuthorityAlert {
            get {
                return ResourceManager.GetString("SettingsAuthorityAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Managing Monitoring Service Time Remaining과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadAvailableTime {
            get {
                return ResourceManager.GetString("SettingsItemHeadAvailableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To check remaining time of Service Point 2.0 monitoring agents과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadAvailableTimeExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadAvailableTimeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download &amp; Update과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadDownload {
            get {
                return ResourceManager.GetString("SettingsItemHeadDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To download Service Point 2.0 related updates과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadDownloadExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadDownloadExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mobile Alert Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadMobileAlerts {
            get {
                return ResourceManager.GetString("SettingsItemHeadMobileAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To configure alerts of mobile push service for the alerts from Service Point Dashboard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadMobileAlertsExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadMobileAlertsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Process Monitoring Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadProcessInstance {
            get {
                return ResourceManager.GetString("SettingsItemHeadProcessInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To register, or delete a user-defined process from any target server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadProcessInstanceExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadProcessInstanceExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert Management, based on Performance Counters과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadRuleEditorByPCID {
            get {
                return ResourceManager.GetString("SettingsItemHeadRuleEditorByPCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To configure alerts, and their conditions, based on performance counters과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadRuleEditorByPCIDExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadRuleEditorByPCIDExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadRulesEditor {
            get {
                return ResourceManager.GetString("SettingsItemHeadRulesEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To configure alerts, and their conditions, such as threshold, based on servers, and severity과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadRulesEditorExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadRulesEditorExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assigning users to monitoring servers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadServerMember {
            get {
                return ResourceManager.GetString("SettingsItemHeadServerMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To manage users, and servers to monitor. Service Point Dashboard will display information of servers only for assinged users.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadServerMemberExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadServerMemberExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monitoring Servers Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadServerRegister {
            get {
                return ResourceManager.GetString("SettingsItemHeadServerRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To register, or edit server information to monitor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadServerRegisterExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadServerRegisterExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monitoring Users Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadUserManagement {
            get {
                return ResourceManager.GetString("SettingsItemHeadUserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To register, or delete users of this monitoring group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemHeadUserManagementExplanation {
            get {
                return ResourceManager.GetString("SettingsItemHeadUserManagementExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monitoring Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemMonitoringManagement {
            get {
                return ResourceManager.GetString("SettingsItemMonitoringManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Servers Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemServerManagement {
            get {
                return ResourceManager.GetString("SettingsItemServerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Users Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsItemUserManagement {
            get {
                return ResourceManager.GetString("SettingsItemUserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To Settings Main Page과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsLinkHome {
            get {
                return ResourceManager.GetString("SettingsLinkHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Service Point 2.0 Administrations과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingsSubject {
            get {
                return ResourceManager.GetString("SettingsSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Missing required fields - Title과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StrMailHeaderEmtyAlert {
            get {
                return ResourceManager.GetString("StrMailHeaderEmtyAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Missing required fields - Inquiry details과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StrMailMessageEmtyAlert {
            get {
                return ResourceManager.GetString("StrMailMessageEmtyAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Missing required fields - Email Address과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StrMailSenderEmtyAlert {
            get {
                return ResourceManager.GetString("StrMailSenderEmtyAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your inquiry has been submitted successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StrMailSuccessSendAlert {
            get {
                return ResourceManager.GetString("StrMailSuccessSendAlert", resourceCulture);
            }
        }
    }
}
